services:
  gateway:
    container_name: gateway_container
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile.dev
      target: development
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /user/src/app/node_modules
    networks:
      - app-network
    command: npm run start:dev:gateway

  auth:
    container_name: auth_container
    build:
      context: .
      dockerfile: apps/auth/Dockerfile.dev
      target: development
    ports:
      - '50051:50000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: npm run start:dev:auth

  mongodb-primary:
    container_name: mongodb_primary_container
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27017:27017'
  mongodb-secondary:
    container_name: mongodb_secondary_container
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local

networks:
  app-network:
    driver: bridge
